import { runReadiness } from './readiness-cloud.mjs';
import fs from 'node:fs';
import path from 'node:path';
import { createRequire } from 'node:module';
import { createHash } from 'node:crypto';
const require=createRequire(path.join(process.env.LUNIS_TOOLS,'package.json'));
const {chromium,expect}=require('@playwright/test');
const {createClient}=require('@supabase/supabase-js');
const API='https://eomffuubhvsfzitphwbk.supabase.co';
const KEY='sb_publishable_SdnZnzZZ5GJlkgkQLW7Zrw_H7_1COie';
const SITE='https://martin-hausleitner.github.io/lunis-status/experience/';
const OUT=path.resolve('proof');fs.mkdirSync(OUT,{recursive:true});
const report={build:'clean-20260922-1',source_commit:process.env.GITHUB_SHA,site:SITE,started_at:new Date().toISOString(),checks:[],screenshots:[],cleanup:null};
const sensitive=[];let fixture,browser;const clients=[];
const redact=text=>sensitive.reduce((s,v)=>v?s.split(v).join('[REDACTED]'):s,String(text)).replace(/(access_token|refresh_token|authorization)["']?\s*[:=]\s*[^,\s]+/gi,'$1=[REDACTED]');
function mask(s){sensitive.push(s);console.log('::add-mask::'+s);}
async function step(name,fn){const start=Date.now();try{const detail=await fn();report.checks.push({name,status:'passed',duration_ms:Date.now()-start,...(detail?{detail}:{} )});console.log('PASS '+name);}catch(e){report.checks.push({name,status:'failed',duration_ms:Date.now()-start,error:redact(e.message).slice(0,900)});throw e;}}
async function oidc(){const url=new URL(process.env.ACTIONS_ID_TOKEN_REQUEST_URL);url.searchParams.set('audience','urn:lunis:ci');const r=await fetch(url,{headers:{Authorization:'Bearer '+process.env.ACTIONS_ID_TOKEN_REQUEST_TOKEN}});if(!r.ok)throw Error('GitHub OIDC unavailable');const {value}=await r.json();mask(value);return value;}
async function fixtureAction(action){const token=await oidc();const r=await fetch(API+'/functions/v1/lunis-ci-fixture',{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify({action})});const j=await r.json();if(!r.ok)throw Error('CI fixture '+action+' failed: '+r.status+' '+JSON.stringify(j));return j;}
async function clientFor(role){const c=createClient(API,KEY,{auth:{persistSession:false,autoRefreshToken:false}});const s=fixture.users[role];const {data,error}=await c.auth.signInWithPassword({email:s.email,password:s.password});if(error)throw Error('API sign-in failed for '+role);mask(data.session.access_token);mask(data.session.refresh_token);clients.push(c);return c;}
const rpc=(c,a,p={})=>c.rpc('lunis_portal',{p_action:a,p_payload:{workspace_id:fixture.workspace_id,...p}});
async function signIn(page,who,target=SITE){await page.goto(target,{waitUntil:'networkidle'});await page.getByLabel('E-Mail',{exact:true}).fill(fixture.users[who].email);await page.getByLabel('Passwort',{exact:true}).fill(fixture.users[who].password);await page.getByRole('button',{name:'Anmelden',exact:true}).click();await expect(page.locator('body')).toHaveAttribute('data-auth','signed-in',{timeout:30000});}
async function nav(page,view){await page.locator('#app-nav [data-view="'+view+'"]').click();await expect(page.locator('#current-view')).toHaveText({overview:'Übersicht',feedback:'Kommentare',documents:'Dokumente',files:'Berichte & Dateien',admin:'Administration'}[view],{timeout:20000});}
async function shot(page,name){await page.screenshot({path:path.join(OUT,name+'.png'),fullPage:true,animations:'disabled'});report.screenshots.push(name+'.png');}
async function waitSite(){const expected=JSON.parse(fs.readFileSync('experience/build.json','utf8'));for(let i=0;i<40;i++){try{const deployed=await fetch(SITE+'build.json?revision='+expected.source_commit,{cache:'no-store'}).then(r=>r.json());if(deployed.source_commit!==expected.source_commit)throw Error('Old deployment');for(const [name,file]of Object.entries(expected.files)){const r=await fetch(SITE+name+'?revision='+expected.source_commit,{cache:'no-store'});if(!r.ok)throw Error('Missing '+name);if(name==='index.html'&&!r.headers.get('content-type')?.includes('text/html'))throw Error('Not HTML');const bytes=Buffer.from(await r.arrayBuffer());if(bytes.length!==file.bytes||createHash('sha256').update(bytes).digest('hex')!==file.sha256)throw Error('Mismatch '+name);}return {files:Object.keys(expected.files).length,source_commit:expected.source_commit};}catch{}await new Promise(r=>setTimeout(r,5000));}throw Error('Published files differ from this exact build');}

try{
 await step('Published frontend is HTML, complete and current',waitSite);
 await step('CI fixture rejects anonymous callers',async()=>{const r=await fetch(API+'/functions/v1/lunis-ci-fixture',{method:'POST',headers:{'Content-Type':'application/json'},body:'{"action":"setup"}'});expect(r.status).toBe(401);});
 fixture=await fixtureAction('setup');for(const u of Object.values(fixture.users))mask(u.password);
 browser=await chromium.launch({headless:true});
 const adminContext=await browser.newContext({viewport:{width:1440,height:1000}}),memberContext=await browser.newContext({viewport:{width:1440,height:1000}});
 const admin=await adminContext.newPage(),member=await memberContext.newPage();const errors=[];admin.on('pageerror',e=>errors.push(e.message));member.on('pageerror',e=>errors.push(e.message));
 await step('Login screen renders canonical branding',async()=>{await admin.goto(SITE);await expect(admin.locator('.brand img')).toBeVisible();await expect(admin.getByRole('heading',{name:'Ihr Projekt. Auf einen Blick.'})).toBeVisible();await expect(admin.locator('#fatal')).toBeHidden();await shot(admin,'01-login-desktop');});
 await step('Incorrect password fails without granting access',async()=>{await admin.getByLabel('E-Mail',{exact:true}).fill(fixture.users.admin.email);await admin.getByLabel('Passwort',{exact:true}).fill('intentionally-wrong-password');await admin.getByRole('button',{name:'Anmelden',exact:true}).click();await expect(admin.locator('#auth-error')).toBeVisible();await expect(admin.locator('#signed-app')).toBeHidden();});
 await step('Admin and member sign in in isolated browser sessions',async()=>{await signIn(admin,'admin');await signIn(member,'member');await expect(admin.locator('body')).toHaveAttribute('data-role','owner');await expect(member.locator('body')).toHaveAttribute('data-role','member');await expect(admin.locator('#admin-nav')).toBeVisible();await expect(member.locator('#admin-nav')).toBeHidden();await shot(admin,'02-admin-overview');await shot(member,'03-member-overview');});
 await step('Both sessions have an active Realtime subscription',async()=>{await expect(admin.locator('body')).toHaveAttribute('data-realtime','SUBSCRIBED',{timeout:30000});await expect(member.locator('body')).toHaveAttribute('data-realtime','SUBSCRIBED',{timeout:30000});});
 const text='E2E '+fixture.run_key+' · Gemeinsame Rückfrage <img src=x onerror=alert(1)>',reply='E2E '+fixture.run_key+' · Antwort der Administration';
 await step('Member comment appears in admin via a real Realtime event',async()=>{await nav(admin,'feedback');await nav(member,'feedback');const events=Number(await admin.locator('body').getAttribute('data-live-events'));await member.getByLabel('Ihr Kommentar').fill(text);await member.getByRole('button',{name:'Kommentar speichern'}).click();await expect(admin.locator('#comment-stream')).toContainText(text,{timeout:25000});await expect.poll(async()=>Number(await admin.locator('body').getAttribute('data-live-events')),{timeout:25000}).toBeGreaterThan(events);expect(await admin.locator('.comment img').count()).toBe(0);});
 await step('Admin reply appears in member without a page reload',async()=>{const events=Number(await member.locator('body').getAttribute('data-live-events'));await admin.getByLabel('Ihr Kommentar').fill(reply);await admin.getByRole('button',{name:'Kommentar speichern'}).click();await expect(member.locator('#comment-stream')).toContainText(reply,{timeout:25000});await expect.poll(async()=>Number(await member.locator('body').getAttribute('data-live-events'))).toBeGreaterThan(events);});
 await step('Admin status change reaches member live',async()=>{const item=admin.locator('.comment').filter({hasText:text});await item.getByLabel('Kommentarstatus').selectOption('done');await expect(member.locator('.comment').filter({hasText:text})).toContainText('Erledigt',{timeout:25000});await shot(admin,'04-admin-comments');await shot(member,'05-member-comments');});
 await step('Session and comments survive reload',async()=>{await member.reload({waitUntil:'networkidle'});await expect(member.locator('body')).toHaveAttribute('data-auth','signed-in');await expect(member.locator('#comment-stream')).toContainText(text);await expect(member.locator('#comment-stream')).toContainText(reply);});
 const adminAPI=await clientFor('admin'),memberAPI=await clientFor('member'),viewerAPI=await clientFor('viewer'),outsiderAPI=await clientFor('outsider');
 await step('Member cannot call administrative RPC or change own role',async()=>{for(const a of ['admin.members','admin.audit','admin.role']){const {error}=await rpc(memberAPI,a,{user_id:fixture.users.member.id,role:'owner'});expect(error).toBeTruthy();}const {error}=await memberAPI.from('lunis_memberships').update({role:'owner'}).eq('user_id',fixture.users.member.id);expect(error).toBeTruthy();});
 await step('Viewer cannot create comments; outsider cannot read workspace data',async()=>{expect((await rpc(viewerAPI,'feedback.create',{category:'general',body:'Not allowed'})).error).toBeTruthy();const outsider=await outsiderAPI.from('lunis_feedback').select('id').eq('workspace_id',fixture.workspace_id);expect(outsider.error).toBeNull();expect(outsider.data).toEqual([]);expect((await rpc(outsiderAPI,'document.list')).error).toBeTruthy();const anon=createClient(API,KEY,{auth:{persistSession:false}});expect((await rpc(anon,'feedback.list')).error).toBeTruthy();});
 await step('Comment retry is idempotent',async()=>{const request_id=crypto.randomUUID();const p={category:'general',body:'E2E idempotency '+fixture.run_key,request_id};const a=await rpc(memberAPI,'feedback.create',p),b=await rpc(memberAPI,'feedback.create',p);expect(a.error).toBeNull();expect(b.error).toBeNull();expect(a.data.id).toBe(b.data.id);});
 const title='E2E Testfreigabe '+fixture.run_key,body='Synthetisches Testdokument für Lunis. Keine rechtsgeschäftliche Erklärung. Prüfumfang: Versionsfreigabe und Speicherung einer Testbestätigung.';
 let documentId;
 await step('Admin creates a draft; member cannot see the draft',async()=>{await nav(admin,'documents');await admin.getByRole('button',{name:'Neues Dokument'}).click();await admin.getByLabel('Dokumenttitel').fill(title);await admin.getByLabel('Dokumentinhalt').fill(body);await admin.getByRole('button',{name:'Entwurf speichern'}).click();await expect(admin.locator('#dialog-title')).toHaveText(title);const docs=await rpc(adminAPI,'document.list');expect(docs.error).toBeNull();documentId=docs.data.find(d=>d.title===title).id;const hidden=await rpc(memberAPI,'document.get',{id:documentId});expect(hidden.error).toBeTruthy();const direct=await memberAPI.from('lunis_documents').select('id').eq('id',documentId);expect(direct.data).toEqual([]);});
 await step('Admin publishes a version; member can read it',async()=>{admin.once('dialog',d=>d.accept());await admin.getByRole('button',{name:'Version freigeben',exact:true}).click();await expect(admin.locator('#dialog-content')).toContainText('Version 1');await admin.getByRole('button',{name:'Dialog schließen'}).click();await nav(member,'documents');await member.locator('.list-card').filter({hasText:title}).getByRole('button',{name:/Ansehen/}).click();await expect(member.locator('#document-body')).toHaveText(body);});
 await step('Member draws and saves a synthetic test signature',async()=>{const canvas=member.locator('#signature'),box=await canvas.boundingBox();await member.mouse.move(box.x+30,box.y+60);await member.mouse.down();await member.mouse.move(box.x+70,box.y+25);await member.mouse.move(box.x+110,box.y+90);await member.mouse.move(box.x+180,box.y+40);await member.mouse.up();await member.locator('#signature-consent').check();await member.getByRole('button',{name:'Testbestätigung speichern'}).click();await expect(member.locator('#dialog-content')).toContainText('gezeichnet');await shot(member,'06-test-document-signature');});
 await step('Document export preserves version hash and test flag',async()=>{const x=await rpc(memberAPI,'document.export',{id:documentId});expect(x.error).toBeNull();expect(x.data.document.is_test).toBe(true);expect(x.data.signatures).toHaveLength(1);expect(x.data.signatures[0].is_test).toBe(true);const sha=createHash('sha256').update(body).digest('hex');expect(x.data.version.content_sha256).toBe(sha);expect(x.data.signatures[0].content_sha256).toBe(sha);const p=member.waitForEvent('download');await member.getByRole('button',{name:'Nachweise als JSON'}).click();const d=await p;expect(d.suggestedFilename()).toBe('Lunis-Dokumentnachweis.json');await member.getByRole('button',{name:'Dialog schließen'}).click();});
 await step('Unresolved document placeholders block publication',async()=>{const d=await rpc(adminAPI,'document.save',{title:'Unvollständiger CI-Entwurf',kind:'test',body_template:'Pflichtangabe: {{auftraggeber}}',required_fields:[],fields:{},is_test:true});expect(d.error).toBeNull();expect((await rpc(adminAPI,'document.publish',{id:d.data.id})).error).toBeTruthy();});
 const zip=Buffer.from('UEsDBBQAAAAIAPtMNl0RVV2DOwAAADoAAAAOAAAATHVuaXMtVGVzdC50eHQLrswryUgtySxOzkgtUvApzcss1g1JLS7RU/BOzcxLVfAuzUtJzdNVyE8BSkeVpifmpRenJJak5ukBAFBLAQIUAxQAAAAIAPtMNl0RVV2DOwAAADoAAAAOAAAAAAAAAAAAAACAAQAAAABMdW5pcy1UZXN0LnR4dFBLBQYAAAAAAQABADwAAABnAAAAAAA=','base64');
 await step('Admin uploads a private ZIP through the UI',async()=>{await nav(admin,'files');await admin.getByRole('button',{name:'Datei hochladen',exact:true}).click();await admin.getByLabel('Titel',{exact:true}).fill('E2E Privatdatei');await admin.locator('#upload-file').setInputFiles({name:'Lunis-Test.zip',mimeType:'application/zip',buffer:zip});await admin.locator('input[name=approved]').check();await admin.getByRole('button',{name:'Datei sicher hochladen'}).click();await expect(admin.locator('#signed-app')).toContainText('E2E Privatdatei',{timeout:30000});await shot(admin,'07-private-files');});
 let resource;
 await step('Member downloads identical bytes; anonymous storage URL is denied',async()=>{await nav(member,'files');await expect(member.locator('#signed-app')).toContainText('E2E Privatdatei');const p=member.waitForEvent('download');await member.getByRole('button',{name:'Herunterladen',exact:true}).click();const d=await p;const bytes=fs.readFileSync(await d.path());expect(createHash('sha256').update(bytes).digest('hex')).toBe(createHash('sha256').update(zip).digest('hex'));const list=await rpc(memberAPI,'resource.list');resource=list.data[0];const r=await fetch(API+'/storage/v1/object/public/lunis-reports/'+resource.storage_path);expect(r.ok).toBe(false);const unauthorized=await outsiderAPI.storage.from('lunis-reports').createSignedUrl(resource.storage_path,60);expect(unauthorized.error).toBeTruthy();});
 await step('Member cannot upload files into an administrative workspace folder',async()=>{const fake=fixture.workspace_id+'/'+createHash('sha256').update('other').digest('hex')+'/blocked.zip';const {error}=await memberAPI.storage.from('lunis-reports').upload(fake,zip,{contentType:'application/zip'});expect(error).toBeTruthy();});
 let invite;
 await step('Admin creates a bound invitation; invited user accepts in separate session',async()=>{await nav(admin,'admin');await admin.getByLabel('E-Mail der eingeladenen Person').fill(fixture.users.invitee.email);await admin.getByRole('button',{name:'Einladungslink erstellen'}).click();await expect(admin.locator('#invite-link')).toBeVisible();invite=await admin.locator('#invite-link').inputValue();mask(invite);const token=new URL(invite).hash.split('=')[1];mask(token);const context=await browser.newContext();const page=await context.newPage();await signIn(page,'invitee',invite);await page.getByRole('button',{name:'Einladung annehmen',exact:true}).click();await expect(page.locator('body')).toHaveAttribute('data-role','member');const invitedAPI=await clientFor('invitee');expect((await rpc(invitedAPI,'invite.accept',{token})).error).toBeTruthy();await context.close();});
 await step('Audit records real actor actions; owner cannot change own owner role',async()=>{const log=await rpc(adminAPI,'admin.audit');expect(log.error).toBeNull();expect(log.data.some(e=>e.event_type==='document.signed')).toBe(true);expect(log.data.some(e=>e.event_type==='invitation.created')).toBe(true);expect((await rpc(adminAPI,'admin.role',{user_id:fixture.users.admin.id,role:'member'})).error).toBeTruthy();await nav(admin,'admin');await shot(admin,'08-administration');});
 await step('Mobile layout and reduced motion work',async()=>{const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,reducedMotion:'reduce'});const page=await context.newPage();await signIn(page,'member');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await shot(page,'09-mobile-overview');await nav(page,'feedback');await expect(page.locator('#comment-stream')).toContainText(text);await shot(page,'10-mobile-comments');await context.close();});
 await step('Mobile logout remains accessible and clears the private session',async()=>{const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});const page=await context.newPage();await signIn(page,'member');await expect(page.getByRole('button',{name:'Abmelden',exact:true})).toBeVisible();await shot(page,'11-mobile-account-controls');await page.getByRole('button',{name:'Abmelden',exact:true}).click();await expect(page.locator('body')).toHaveAttribute('data-auth','signed-out');expect(await page.locator('#signed-app').innerHTML()).toBe('');await expect(page.locator('#realtime')).toContainText('Anmeldung erforderlich');await context.close();});
 await step('PWA caches only the application shell, never Supabase/private files',async()=>{await admin.evaluate(()=>navigator.serviceWorker.ready);const urls=await admin.evaluate(async()=>{const all=[];for(const key of await caches.keys())if(key.startsWith('lunis-shell-'))for(const req of await (await caches.open(key)).keys())all.push(req.url);return all;});expect(urls.length).toBeGreaterThan(2);expect(urls.every(u=>u.startsWith(SITE))).toBe(true);expect(urls.some(u=>u.includes('supabase.co'))).toBe(false);});
 await runReadiness({step,expect,admin,member,adminAPI,memberAPI,viewerAPI,outsiderAPI,fixture,createClient,API,KEY,SITE,OUT,shot,rpc,resource,documentId,signIn});
 await step('Logout clears session and private rendered content',async()=>{await member.getByRole('button',{name:'Abmelden',exact:true}).click();await expect(member.locator('body')).toHaveAttribute('data-auth','signed-out');expect(await member.locator('#signed-app').innerHTML()).toBe('');expect(await member.locator('#dialog-content').innerHTML()).toBe('');await member.reload();await expect(member.locator('#auth-view')).toBeVisible();await expect(member.locator('#signed-app')).toBeHidden();});
 await step('No browser runtime errors',async()=>expect(errors).toEqual([]));
}catch(e){console.error('E2E_FAILURE '+redact(e.message).slice(0,1000));process.exitCode=1;}
finally{
 if(browser)await browser.close();
 try{report.cleanup=await fixtureAction('cleanup');console.log('CI_CLEANUP_OK');}catch(e){report.cleanup={cleaned:false,error:redact(e.message).slice(0,500)};process.exitCode=1;}
 for(const c of clients)await c.auth.signOut().catch(()=>{});
 report.finished_at=new Date().toISOString();report.passed=report.checks.filter(c=>c.status==='passed').length;report.failed=report.checks.filter(c=>c.status==='failed').length;report.status=process.exitCode?'FAILED':'PASSED';
 fs.writeFileSync(path.join(OUT,'cloud-e2e.json'),JSON.stringify(report,null,2));
 console.log('E2E_RESULT '+JSON.stringify({status:report.status,passed:report.passed,failed:report.failed,cleanup:report.cleanup?.cleaned}));
}
