import fs from 'node:fs';
import path from 'node:path';
import http from 'node:http';
import {createHash} from 'node:crypto';
import {createRequire} from 'node:module';
const require=createRequire(path.join(process.env.LUNIS_TOOLS,'package.json'));
const {chromium,expect}=require('@playwright/test');
const LIVE=process.argv.includes('--live');
const ROOT=path.resolve('experience/bericht');
const OUT=path.resolve('proof/report-v4'+(LIVE?'-live':''));fs.mkdirSync(OUT,{recursive:true});
const PAGES=['index','ergebnisse','funktion','kosten','leistung','ablauf','technik','markt','methodik','quellen'];
const mime={'.html':'text/html; charset=utf-8','.css':'text/css','.js':'text/javascript','.svg':'image/svg+xml','.png':'image/png','.json':'application/json','.zip':'application/zip','.csv':'text/csv','.txt':'text/plain'};
let server,browser;let url='https://martin-hausleitner.github.io/lunis-status/experience/bericht/';
const result={scope:LIVE?'published report':'local build on authorized CI browser',build:'bericht-v4-20260922',source_commit:process.env.GITHUB_SHA,started_at:new Date().toISOString(),checks:[],screenshots:[]};
async function step(name,fn){try{await fn();result.checks.push({name,status:'passed'});console.log('REPORT_PASS '+name);}catch(e){result.checks.push({name,status:'failed',error:String(e.message).slice(0,1500)});throw e;}}
async function capture(page,name){for(const section of await page.locator('.section').all())await section.scrollIntoViewIfNeeded();await page.evaluate(()=>window.scrollTo(0,0));await page.waitForTimeout(200);await page.screenshot({path:path.join(OUT,name+'.png'),fullPage:true,animations:'disabled'});result.screenshots.push(name+'.png');}
async function ready(page){await page.waitForFunction(()=>Array.from(document.querySelectorAll('img[src]')).every(i=>i.complete&&i.naturalWidth>0));}
try{
 if(!LIVE){server=http.createServer((req,res)=>{let rel=decodeURIComponent(new URL(req.url,'http://local').pathname);if(rel.endsWith('/'))rel+='index.html';const file=path.resolve(ROOT,'.'+rel);if(!file.startsWith(ROOT+path.sep)||!fs.existsSync(file)||!fs.statSync(file).isFile()){res.writeHead(404).end('Not found');return;}res.writeHead(200,{'Content-Type':mime[path.extname(file)]||'application/octet-stream'});fs.createReadStream(file).pipe(res);});await new Promise(r=>server.listen(0,'127.0.0.1',r));url='http://127.0.0.1:'+server.address().port+'/';}
 else await step('Published report equals this exact build',async()=>{const expected=JSON.parse(fs.readFileSync(path.join(ROOT,'build.json')));let last='not ready';for(let n=0;n<40;n++){try{const actual=await fetch(url+'build.json?revision='+process.env.GITHUB_SHA,{cache:'no-store'}).then(r=>r.json());expect(actual.source_commit).toBe(expected.source_commit);for(const [name,meta] of Object.entries(expected.files)){const r=await fetch(url+name+'?revision='+process.env.GITHUB_SHA,{cache:'no-store'});expect(r.ok).toBe(true);const b=Buffer.from(await r.arrayBuffer());expect(createHash('sha256').update(b).digest('hex')).toBe(meta.sha256);}return;}catch(e){last=e.message;}await new Promise(r=>setTimeout(r,5000));}throw Error(last);});
 browser=await chromium.launch({headless:true});const context=await browser.newContext({viewport:{width:1440,height:1050},reducedMotion:'reduce'});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 for(const key of PAGES)await step('Page '+key+' renders with navigation, assets and no overflow',async()=>{const r=await page.goto(url+key+'.html',{waitUntil:'networkidle'});expect(r.status()).toBe(200);expect(r.headers()['content-type']).toContain('text/html');await expect(page.locator('h1')).toHaveCount(1);await expect(page.locator('.nav-link')).toHaveCount(10);await expect(page.locator('.nav-link[aria-current=page]')).toHaveAttribute('href',key+'.html');await ready(page);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await capture(page,key+'-desktop');});
 await step('Search opens by keyboard and leads to costs',async()=>{await page.keyboard.press('Control+k');await expect(page.locator('#search-dialog')).toBeVisible();await page.locator('#global-search').fill('Kosten');await page.locator('#search-results a[href="kosten.html"]').click();await expect(page).toHaveURL(/kosten[.]html$/);});
 await step('Cost model is transparent, interactive and exportable',async()=>{await expect(page.locator('#roi-hours')).toHaveText('31,25 h');await expect(page.locator('#roi-value')).toHaveText('943,75 €');await expect(page.locator('#roi-months')).toHaveText('6,4 Monate');await page.locator('#roi-people').fill('50');await expect(page.locator('#roi-hours')).toHaveText('62,5 h');await page.locator('#roi-minutes').fill('0');await expect(page.locator('#roi-months')).toHaveText('Kein Ausgleich');await page.locator('#roi-people').fill('-2');await expect(page.locator('#roi-months')).toHaveText('Eingaben prüfen');await page.getByRole('button',{name:'Annahmen zurücksetzen'}).click();const waiting=page.waitForEvent('download');await page.locator('[data-export-roi]').click();const d=await waiting;const j=JSON.parse(fs.readFileSync(await d.path()));expect(j.assumptions.initial).toBe(6000);expect(j.results.hours_per_month).toBe(31.25);expect(j.classification).toContain('Kein garantierter Gewinn');await expect(page.locator('body')).toContainText('Keine Rechnung. Kein Zahlungsnachweis.');});
 await step('Function matrix filters and searches without changing facts',async()=>{await page.goto(url+'funktion.html');await page.locator('[data-filter="proven"]').click();await expect(page.locator('[data-filter-row]:visible')).toHaveCount(6);await page.locator('[data-filter="model"]').click();await expect(page.locator('[data-filter-row]:visible')).toHaveCount(2);await page.locator('[data-filter="all"]').click();await page.locator('#function-search').fill('Scanner bis');await expect(page.locator('[data-filter-row]:visible')).toHaveCount(1);await page.locator('#function-search').fill('not-existing-xyz');await expect(page.locator('#no-results')).toBeVisible();await page.locator('#function-search').fill('');await expect(page.locator('[data-filter-row]:visible')).toHaveCount(16);});
 await step('Historical portal images open and clear on closing',async()=>{await page.goto(url+'ergebnisse.html');await page.locator('[data-image]').first().click();await expect(page.locator('#image-dialog')).toBeVisible();await expect(page.locator('#image-caption')).toContainText('Echter Chromium-Test');await page.getByRole('button',{name:'Bild schließen'}).click();expect(await page.locator('#large-image').getAttribute('src')).toBeNull();});
 await step('Sandboxed teaching demo follows capture, review, book, reset',async()=>{await page.locator('iframe').scrollIntoViewIfNeeded();const f=page.frameLocator('iframe');await expect(f.locator('#demo-review')).toBeDisabled();await f.locator('#demo-capture').click();await expect(f.locator('#d-state')).toHaveText('Rohzeit vorhanden');await f.locator('#demo-review').click();await expect(f.locator('#d-reviewed')).toHaveText('1,5 h');await f.locator('#demo-book').click();await expect(f.locator('#d-state')).toHaveText('Gebucht');await f.locator('#demo-reset').click();await expect(f.locator('#d-count')).toHaveText('0 / 3');await page.locator('iframe').screenshot({path:path.join(OUT,'demo-walkthrough.png')});result.screenshots.push('demo-walkthrough.png');expect(await page.locator('iframe').getAttribute('sandbox')).toBe('allow-scripts');});
 await step('Five-step tour reaches an explicit decision',async()=>{await page.goto(url+'index.html?tour=1');for(let n=1;n<=5;n++){await expect(page.locator('#tour-count')).toHaveText('· '+n+' / 5');if(n<5)await page.locator('#tour-next').click();}await page.getByRole('button',{name:'Tour beenden'}).click();await expect(page.locator('.tourbar')).toBeHidden();});
 await step('Notes are expandable and sourced; CSV/JSON exports parse',async()=>{await page.goto(url+'methodik.html');await expect(page.locator('details')).toHaveCount(8);await page.locator('summary').first().click();await expect(page.locator('#note-N01')).toBeVisible();await page.locator('[data-copy="note-N01"]').click();await expect(page.locator('.toast')).toHaveText('Text kopiert.');await page.goto(url+'quellen.html');await expect(page.locator('.source-card')).toHaveCount(13);const json=await fetch(url+'exports/Quellen.json').then(r=>r.json());expect(json).toHaveLength(13);const csv=await fetch(url+'exports/Leistungsblatt.csv').then(r=>r.text());expect(csv).toContain('ca. 5,0');expect(csv).toContain('keine neue Zeitmessung');});
 for(const key of ['index','kosten','funktion','ergebnisse'])await step('Mobile '+key+' keeps content and navigation accessible',async()=>{const c=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,reducedMotion:'reduce'});const p=await c.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto(url+key+'.html',{waitUntil:'networkidle'});expect(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await expect(p.locator('.sidebar')).toBeHidden();await p.getByRole('button',{name:'Navigation öffnen'}).click();await expect(p.locator('.sidebar')).toBeVisible();await p.locator('.sidebar-shade').click({position:{x:380,y:300}});await expect(p.locator('.sidebar')).toBeHidden();await capture(p,key+'-mobile');await c.close();});
 await step('Reduced motion and print do not hide report content',async()=>{await page.goto(url+'index.html');expect(await page.locator('.tile').evaluate(e=>getComputedStyle(e).animationName)).toBe('none');await page.goto(url+'kosten.html');await page.pdf({path:path.join(OUT,'kosten-print-proof.pdf'),format:'A4',printBackground:true});await page.emulateMedia({media:'print'});await expect(page.locator('.sidebar')).toBeHidden();await expect(page.locator('h1')).toBeVisible();await page.emulateMedia({media:'screen'});});
 if(!LIVE)await step('Downloaded report works as offline file without external requests',async()=>{const p=await context.newPage();const external=[];p.on('request',r=>{if(/^https?:/.test(r.url()))external.push(r.url());});await p.goto('file://'+path.join(ROOT,'index.html'),{waitUntil:'load'});await expect(p.locator('h1')).toContainText('Was gebaut wurde');await p.locator('[data-search]').click();await expect(p.locator('#search-dialog')).toBeVisible();expect(external).toEqual([]);await p.close();});
 await step('No JavaScript runtime errors in report pages',async()=>expect(errors).toEqual([]));
}catch(e){console.error('REPORT_FAILURE '+String(e.message).slice(0,1600));process.exitCode=1;}
finally{if(browser)await browser.close();if(server)await new Promise(r=>server.close(r));result.finished_at=new Date().toISOString();result.passed=result.checks.filter(x=>x.status==='passed').length;result.failed=result.checks.filter(x=>x.status==='failed').length;result.status=process.exitCode?'FAILED':'PASSED';fs.writeFileSync(path.join(OUT,'report-e2e.json'),JSON.stringify(result,null,2));console.log('REPORT_RESULT '+JSON.stringify({status:result.status,passed:result.passed,failed:result.failed,screenshots:result.screenshots.length}));}
